;
; File generated by cc65 v 2.19 - Git 394d3b1
;
	.fopt		compiler,"cc65 v 2.19 - Git 394d3b1"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_pal_bg
	.import		_pal_spr
	.import		_ppu_wait_nmi
	.import		_ppu_off
	.import		_bank_spr
	.import		_set_vram_buffer
	.import		_one_vram_buffer
	.export		_temp0
	.export		_temp1
	.export		_temp2
	.export		_temp3
	.export		_temp4
	.export		_global_i
	.export		_global_j
	.export		_bgPalette
	.export		_sprPalette
	.export		_main

.segment	"RODATA"

_bgPalette:
	.byte	$09
	.byte	$1A
	.byte	$0F
	.byte	$30
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
_sprPalette:
	.byte	$00
	.byte	$06
	.byte	$0F
	.byte	$30
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$00

.segment	"BSS"

_temp0:
	.res	1,$00
_temp1:
	.res	1,$00
_temp2:
	.res	1,$00
_temp3:
	.res	1,$00
_temp4:
	.res	1,$00
_global_i:
	.res	1,$00
_global_j:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; ppu_off(); //screen off
;
	jsr     _ppu_off
;
; pal_bg(bgPalette);
;
	lda     #<(_bgPalette)
	ldx     #>(_bgPalette)
	jsr     _pal_bg
;
; pal_spr(sprPalette);
;
	lda     #<(_sprPalette)
	ldx     #>(_sprPalette)
	jsr     _pal_spr
;
; bank_spr(1);
;
	lda     #$01
	jsr     _bank_spr
;
; set_vram_buffer();
;
	jsr     _set_vram_buffer
;
; temp0 = 0;
;
	lda     #$00
	sta     _temp0
;
; temp1 = 0;
;
	sta     _temp1
;
; global_j = 3;
;
	lda     #$03
	sta     _global_j
;
; global_i = 0;
;
	lda     #$00
	sta     _global_i
;
; ppu_wait_nmi();
;
L0002:	jsr     _ppu_wait_nmi
;
; temp0 = 0;
;
	lda     #$00
	sta     _temp0
;
; for(; global_j < 30; ++global_j) {
;
L0010:	lda     _global_j
	cmp     #$1E
	bcs     L0002
;
; for(; global_i < 32; ++global_i) {
;
L0011:	lda     _global_i
	cmp     #$20
	bcs     L0012
;
; one_vram_buffer(8 + (((global_i & 0b1) ^ (global_j & 0b1)) << 1), NTADR_A(global_i, global_j));
;
	and     #$01
	jsr     pusha0
	lda     _global_j
	and     #$01
	jsr     tosxora0
	asl     a
	clc
	adc     #$08
	jsr     pusha
	ldx     #$00
	lda     _global_j
	jsr     aslax4
	stx     tmp1
	asl     a
	rol     tmp1
	sta     ptr1
	lda     _global_i
	ora     ptr1
	pha
	lda     tmp1
	ora     #$20
	tax
	pla
	jsr     _one_vram_buffer
;
; ++temp0;
;
	inc     _temp0
;
; if(temp0 > 30) goto here;
;
	lda     _temp0
	cmp     #$1F
	bcs     L0002
;
; for(; global_i < 32; ++global_i) {
;
	inc     _global_i
	jmp     L0011
;
; global_i = 0;
;
L0012:	lda     #$00
	sta     _global_i
;
; for(; global_j < 30; ++global_j) {
;
	inc     _global_j
	jmp     L0010

.segment	"RODATA"

M0001:
	.word	$0000

.endproc

