;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


music_music_data:
	.byte 4
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; Start Game
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,153,128 ; Normal Game
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,204,170 ; Game End
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256 ; Tiles Updating

@instruments:
	.word @env1,@env0,@env0,@env2
	.word @env1,@env0,@env0,@env0
	.word @env1,@env0,@env0,@env3

@samples:
	.byte $00+.lobyte(FT_DPCM_PTR),$18,$0f	;1
	.byte $00+.lobyte(FT_DPCM_PTR),$18,$00	;2
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;3
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;4
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;5
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;6
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;7
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;8
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;9
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;10
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;11
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;12
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;13
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;14
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;15
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;16
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;17
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;18
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;19
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;20
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;21
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;22
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;23
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;24
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;25
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;26
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;27
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;28
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;29
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;30
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;31
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;32
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;33
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;34
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;35
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;36
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;37
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;38
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;39
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;40
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;41
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;42
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;43
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;44
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;45
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;46
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;47
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;48
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;49
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;50
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;51
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;52
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;53
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;54
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;55
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;56
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;57
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;58
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;59
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;60
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;61
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;62
	.byte $00+.lobyte(FT_DPCM_PTR),$00,$00	;63

@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c0,$cf,$00,$01
@env2:
	.byte $c2,$00,$00
@env3:
	.byte $c1,$00,$00


; Start Game
@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $78,$61,$80,$28,$83,$2b,$83,$2e,$83,$62,$31,$ab
	.byte $fd
	.word @song0ch0loop

; Start Game
@song0ch1:
@song0ch1loop:
@ref1:
	.byte $bf
	.byte $fd
	.word @song0ch1loop

; Start Game
@song0ch2:
@song0ch2loop:
@ref2:
	.byte $80,$04,$83,$07,$83,$0a,$83,$0d,$ab
	.byte $fd
	.word @song0ch2loop

; Start Game
@song0ch3:
@song0ch3loop:
@ref3:
	.byte $bf
	.byte $fd
	.word @song0ch3loop

; Start Game
@song0ch4:
@song0ch4loop:
@ref4:
	.byte $bf
	.byte $fd
	.word @song0ch4loop


; Normal Game
@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref5:
	.byte $97
@ref6:
	.byte $97
@ref7:
	.byte $76,$82,$1f,$89,$1d,$87,$1f
@ref8:
	.byte $93,$00,$81
@ref9:
	.byte $97
@ref10:
	.byte $97
@ref11:
	.byte $74,$1a,$89,$19,$87,$1b
@ref12:
	.byte $93,$00,$81
	.byte $fd
	.word @song1ch0loop

; Normal Game
@song1ch1:
@song1ch1loop:
@ref13:
	.byte $97
@ref14:
	.byte $97
@ref15:
	.byte $74,$82,$13,$89,$14,$87,$16
@ref16:
	.byte $93,$00,$81
@ref17:
	.byte $97
@ref18:
	.byte $97
@ref19:
	.byte $76,$13,$89,$11,$87,$13
@ref20:
	.byte $93,$00,$81
	.byte $fd
	.word @song1ch1loop

; Normal Game
@song1ch2:
@song1ch2loop:
@ref21:
	.byte $80,$27,$81,$00,$85,$27,$85,$00,$22
@ref22:
	.byte $93,$00,$81
@ref23:
	.byte $24,$89,$25,$85,$00,$27
@ref24:
	.byte $93,$00,$81
@ref25:
	.byte $26,$81,$00,$85,$24,$85,$00,$1f
@ref26:
	.byte $93,$00,$81
@ref27:
	.byte $22,$89,$21,$85,$00,$22
@ref28:
	.byte $93,$00,$81
	.byte $fd
	.word @song1ch2loop

; Normal Game
@song1ch3:
@song1ch3loop:
@ref29:
	.byte $74,$82,$0f,$00,$0c,$00,$0c,$00,$0f,$00,$0c,$00,$0c,$00
@ref30:
	.byte $0f,$00,$0c,$00,$0c,$00,$0f,$00,$0c,$00,$0c,$00
	.byte $ff,$0c
	.word @ref30
	.byte $ff,$0c
	.word @ref30
@ref33:
	.byte $74,$0f,$00,$0c,$00,$0c,$00,$0f,$00,$0c,$00,$0c,$00
	.byte $ff,$0c
	.word @ref30
	.byte $ff,$0c
	.word @ref30
	.byte $ff,$0c
	.word @ref30
	.byte $fd
	.word @song1ch3loop

; Normal Game
@song1ch4:
@song1ch4loop:
@ref37:
	.byte $97
@ref38:
	.byte $97
@ref39:
	.byte $97
@ref40:
	.byte $97
@ref41:
	.byte $97
@ref42:
	.byte $97
@ref43:
	.byte $97
@ref44:
	.byte $97
	.byte $fd
	.word @song1ch4loop


; Game End
@song2ch0:
	.byte $fb,$06
@song2ch0loop:
@ref45:
	.byte $73,$61,$84,$2b,$9d,$29,$95,$2b,$85,$2c,$95,$2c,$99
	.byte $fd
	.word @song2ch0loop

; Game End
@song2ch1:
@song2ch1loop:
@ref46:
	.byte $73,$61,$84,$27,$9d,$26,$95,$27,$9d,$29,$85,$26,$91
	.byte $fd
	.word @song2ch1loop

; Game End
@song2ch2:
@song2ch2loop:
@ref47:
	.byte $80,$27,$81,$2b,$81,$2e,$8d,$2b,$81,$33,$81,$32,$8d,$2e,$85,$30
	.byte $85,$2c,$8d,$2b,$81,$2c,$81,$29,$99
	.byte $fd
	.word @song2ch2loop

; Game End
@song2ch3:
@song2ch3loop:
@ref48:
	.byte $f3
	.byte $fd
	.word @song2ch3loop

; Game End
@song2ch4:
@song2ch4loop:
@ref49:
	.byte $f3
	.byte $fd
	.word @song2ch4loop


; Tiles Updating
@song3ch0:
	.byte $fb,$06
@song3ch0loop:
@ref50:
	.byte $78,$80,$1b
	.byte $fd
	.word @song3ch0loop

; Tiles Updating
@song3ch1:
@song3ch1loop:
@ref51:
	.byte $81
	.byte $fd
	.word @song3ch1loop

; Tiles Updating
@song3ch2:
@song3ch2loop:
@ref52:
	.byte $81
	.byte $fd
	.word @song3ch2loop

; Tiles Updating
@song3ch3:
@song3ch3loop:
@ref53:
	.byte $81
	.byte $fd
	.word @song3ch3loop

; Tiles Updating
@song3ch4:
@song3ch4loop:
@ref54:
	.byte $81
	.byte $fd
	.word @song3ch4loop
