;this file for FamiTone2 libary generated by nsf2data tool

sounds:
	.word @ntsc
	.word @pal
@ntsc:
	.word @sfx_ntsc_0
	.word @sfx_ntsc_1
	.word @sfx_ntsc_2
	.word @sfx_ntsc_3
@pal:
	.word @sfx_pal_0
	.word @sfx_pal_1
	.word @sfx_pal_2
	.word @sfx_pal_3

@sfx_ntsc_0:
	.byte $80,$b8,$81,$70,$82,$00,$03,$81,$4b,$03,$00
@sfx_pal_0:
	.byte $80,$b8,$81,$68,$82,$00,$03,$81,$45,$02,$00
@sfx_ntsc_1:
	.byte $89,$37,$8a,$04,$01,$89,$36,$01,$89,$35,$01,$89,$34,$01,$89,$33
	.byte $01,$89,$32,$00
@sfx_pal_1:
	.byte $89,$37,$8a,$04,$01,$89,$36,$01,$89,$35,$01,$89,$34,$01,$89,$33
	.byte $00
@sfx_ntsc_2:
	.byte $00
@sfx_pal_2:
	.byte $00
@sfx_ntsc_3:
	.byte $00
@sfx_pal_3:
	.byte $00
